### ISSUE TITLE
How i get all image in post. Now get only 4 images

### ISSUE THREAD

**Issue by kawewutchu** [kevinzg/facebook-scraper#161]

**Comment by kawewutchu** [comment]
@kevinzg Can I help you fix this. and how possible I want to download video from a Facebook post.

**Comment by neon-ninja** [comment]
Can you provide a link to the problematic post? Also note that you can use youtube-dl to download videos, see https://github.com/kevinzg/facebook-scraper/blob/master/README.md

**Comment by gaoyunzhi** [comment]
I met this issue also, only the first 4 images are in the post['images']. 

Example url: https://www.facebook.com/transarmy/posts/308391180656067

Thank you for making this project!

**Comment by neon-ninja** [comment]
@gaoyunzhi Thanks - this commit should fix the problem - https://github.com/kevinzg/facebook-scraper/commit/7f2305efe67c43b62accd4dfe177e64abd92051e

**Comment by gaoyunzhi** [comment]
Thank you for the update! I think now we are getting more photos, but the additional photo seems to be wrong.

example post: https://www.facebook.com/transarmy/posts/311640790331106

example result: 

```
{
  'post_id': '311640790331106',
  'text': '@katylpacino',
  'post_text': '@katylpacino',
  'shared_text': '',
  'time': datetime.datetime(2021,
  5,
  3,
  7,
  30,
  7),
  'image': 'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182192252_311640423664476_4943039830878416363_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=DXp6T2YDyDYAX8x6r3c&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=0c8ee0e1b7a2b8c517c0c96be25ba27e&oe=60B4EABB',
  'image_lowquality': 'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/s320x320/182192252_311640423664476_4943039830878416363_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=DXp6T2YDyDYAX8x6r3c&_nc_ht=scontent-sjc3-1.xx&tp=9&oh=3c7bcfc8ccc8bf82cfc81c30cae43748&oe=60B73FC0',
  'images': [
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182192252_311640423664476_4943039830878416363_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=DXp6T2YDyDYAX8x6r3c&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=0c8ee0e1b7a2b8c517c0c96be25ba27e&oe=60B4EABB',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182151209_311640486997803_5543981058982086722_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=Ad6lYK3b5wMAX8AB5Ih&_nc_oc=AQkOKKDc_E5wdOg_GfCCo7HCJPsrCtMPXBCVzV9x0Wt1b_IYnZt1Dc30Yse2dekxHTE&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=1df37ebeded9d767137a5b0e16161810&oe=60B712DE',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182266479_311640516997800_1816134662371228066_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=110474&_nc_ohc=6zjy-aSu_0UAX_lGieN&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=1866029cf03338b5f085c0af966f1f38&oe=60B78DE4',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182023920_311640553664463_2357805205459150479_n.jpg?_nc_cat=102&ccb=1-3&_nc_sid=110474&_nc_ohc=qzhKPyWes0IAX9gCiZ6&_nc_oc=AQnOF2H-r8kxTyklP9b0zhAhSrgF_wzID9Hj43udU52_bbJRlyrAVbhJU5F3QihV6qI&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=64c790b7a1cb5720f8e9f3ce925ceb86&oe=60B6C0CD',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182266479_311640516997800_1816134662371228066_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=110474&_nc_ohc=6zjy-aSu_0UAX_lGieN&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=1866029cf03338b5f085c0af966f1f38&oe=60B78DE4',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182151209_311640486997803_5543981058982086722_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=Ad6lYK3b5wMAX8AB5Ih&_nc_oc=AQkOKKDc_E5wdOg_GfCCo7HCJPsrCtMPXBCVzV9x0Wt1b_IYnZt1Dc30Yse2dekxHTE&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=1df37ebeded9d767137a5b0e16161810&oe=60B712DE',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182192252_311640423664476_4943039830878416363_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=DXp6T2YDyDYAX8x6r3c&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=0c8ee0e1b7a2b8c517c0c96be25ba27e&oe=60B4EABB',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/182249958_311615340333651_5187974675392747973_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=67gEevg231sAX9h1pWM&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=8f7dc214c3759fa8e8bc22fdf1ba7fd2&oe=60B668DB',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/181819438_311614363667082_5336170164909086666_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=Huh_LGnnmbQAX_-24nh&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=592f975585670506b2300edc6c03c370&oe=60B76A4D',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/181951279_311598480335337_11845063156394839_n.jpg?_nc_cat=108&ccb=1-3&_nc_sid=110474&_nc_ohc=uI316FzqjVAAX9_VONf&_nc_ht=scontent-sjc3-1.xx&tp=14&oh=e860f219264e2452d7e412e71fcb47e2&oe=60B4970A'
  ],
  'images_lowquality': [
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/s320x320/182192252_311640423664476_4943039830878416363_n.jpg?_nc_cat=107&ccb=1-3&_nc_sid=110474&_nc_ohc=DXp6T2YDyDYAX8x6r3c&_nc_ht=scontent-sjc3-1.xx&tp=9&oh=3c7bcfc8ccc8bf82cfc81c30cae43748&oe=60B73FC0',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p110x80/182151209_311640486997803_5543981058982086722_n.jpg?_nc_cat=104&ccb=1-3&_nc_sid=110474&_nc_ohc=Ad6lYK3b5wMAX8AB5Ih&_nc_oc=AQkOKKDc_E5wdOg_GfCCo7HCJPsrCtMPXBCVzV9x0Wt1b_IYnZt1Dc30Yse2dekxHTE&_nc_ht=scontent-sjc3-1.xx&tp=3&oh=7445c360b07422c3475373d8413bdb0a&oe=60B5527A',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p110x80/182266479_311640516997800_1816134662371228066_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=110474&_nc_ohc=6zjy-aSu_0UAX_lGieN&_nc_ht=scontent-sjc3-1.xx&tp=3&oh=71e211541a321abbe6d0e061bbdb3c5e&oe=60B71E48',
    'https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-0/cp0/e15/q65/p110x80/182023920_311640553664463_2357805205459150479_n.jpg?_nc_cat=102&ccb=1-3&_nc_sid=110474&_nc_ohc=qzhKPyWes0IAX9gCiZ6&_nc_oc=AQnOF2H-r8kxTyklP9b0zhAhSrgF_wzID9Hj43udU52_bbJRlyrAVbhJU5F3QihV6qI&_nc_ht=scontent-sjc3-1.xx&tp=3&oh=357489bf3b776f2cf01675de823a1ecf&oe=60B44EE9'
  ],
  'video': None,
  'video_thumbnail': None,
  'video_id': None,
  'likes': 0,
  'comments': 0,
  'shares': 209,
  'post_url': 'https://facebook.com/story.php?story_fbid=311640790331106&id=100179361477251',
  'link': None,
  'user_id': '100179361477251',
  'username': 'Trans Army',
  'user_url': 'https://facebook.com/transarmy/?__tn__=C-R',
  'is_live': False,
  'factcheck': None,
  'shared_post_id': None,
  'shared_time': None,
  'shared_user_id': None,
  'shared_username': None,
  'shared_post_url': None,
  'available': True,
  'comments_full': None,
  'reactors': None,
  'w3_fb_url': None
}
```

**Comment by neon-ninja** [comment]
Surfacing image alt text might be useful in debugging this, and also a useful feature

**Comment by neon-ninja** [comment]
@gaoyunzhi https://github.com/kevinzg/facebook-scraper/commit/871c762764e611a4f2dfc2345f79d88f81a84987 should fix this, give it a try

**Comment by enaserianhanzaei** [comment]
@neon-ninja 

Hi, thanks for the amazing library. However, i still have problems with scraping the image posts when there are more than 4,5 images (when you have to click to open all the images), do you have any idea how to fix that?

for example in this url: https://www.facebook.com/groups/1166154663436469, it only returns 5 images

**Comment by neon-ninja** [comment]
Duplicate comment of https://github.com/kevinzg/facebook-scraper/issues/231#issuecomment-845871874
