### ISSUE TITLE
Profile: #friends, #followers and #following

### ISSUE THREAD

**Issue by 0x8e5afe** [kevinzg/facebook-scraper#536]
Hello, currently the "get_profile()" function does not return the number of friends, the number of followers and the number of following people. I think that these two fields are really important in some situations, so I suggest you to add them. Furthermore, similarly to the option "Friends=True", you can put another two options: "Followers=True" and "Following=True" to obtain the list of followers/following people for that profile.

Thanks!

**Comment by neon-ninja** [comment]
Try latest master

**Comment by neon-ninja** [comment]
@giuseppe-toscano try latest master. With latest master and this test code:

```python
pprint(get_profile("rachellouiseflood", cookies="cookies.json", followers=5, following=5, friends=5))
```

I get:

```python
{'Basic Info': {'Birthday': 'December 3', 'Gender': 'Female'},
 'Contact Info': {'Facebook': '/rachellouiseflood'},
 'Education': {'High School': 'Alfriston College'},
 'Family Members': {'Aunt': 'Raewyn Hayward'},
 'Follower_count': 814,
 'Followers': [{'link': '/unclemattman',
                'name': 'Matt Schrödter',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p57x57/67139481_10157317504777808_5010641871240691712_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=SvDywPlmEsYAX84-mqQ&_nc_ht=scontent.fakl8-1.fna&oh=d678510e2930ad47345aae047bfcdaa9&oe=61A44EE5',
                'tagline': ''},
               {'link': '/kennith.wood.9',
                'name': 'Kennith Wood',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/154332553_10157994797361220_8488654351291147327_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=UOJ1SyjvA1MAX8CYHR-&_nc_oc=AQmUroDiLhpHRLAf-7M4BSpTLfstv0CEUD3JyVDGRz3LqBi1KNUl1_lgUXKOBxfnlTI&_nc_ht=scontent.fakl8-1.fna&oh=f2eef42196fbf9b6d0b176a4ae22e629&oe=61A49E37',
                'tagline': ''},
               {'link': '/profile.php?id=514655255',
                'name': 'Raj Patel',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/93269788_10157932231025256_7891992532270186496_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=8yEaryRkzEQAX-uCepv&_nc_ht=scontent.fakl8-1.fna&oh=491cd866bc6e5960273ff418a6722bf3&oe=61A5D50B',
                'tagline': ''},
               {'link': '/kevin.harvey.9022',
                'name': 'Kevin Harvey',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/c0.23.60.60a/p60x60/158189205_10159209569137154_3721385072491049197_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=ZlQyBvULpdYAX-7iPqh&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=26ffc5fcc1466adcf92850ba8e573a00&oe=61A6964F',
                'tagline': ''},
               {'link': '/james.r.lindsay.nz',
                'name': 'James Lindsay',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/166628138_10158387882524412_489654457111958203_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=Mi8f6mrZZhAAX9IW1BI&_nc_ht=scontent.fakl8-1.fna&oh=b4d4f2c9ffcbcf5bd96901f751e6afef&oe=61A3063D',
                'tagline': ''},
               {'link': '/bruce.seumanu',
                'name': 'Pulusea Yeng Tung-Seumanu',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/246488448_10159420573647528_2032720078292613797_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=UTur3_b8hx4AX_51FIh&_nc_ht=scontent.fakl8-1.fna&oh=d147067253e6c7f8bd98bbba809e5030&oe=61A4F214',
                'tagline': ''},
               {'link': '/justin.linn.754',
                'name': 'Justin Linn',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.18169-1/cp0/e15/q65/p60x60/12190873_10153373174373477_5994635005043630990_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=cTQvfW-wIkoAX-lQ8Az&_nc_ht=scontent.fakl8-1.fna&oh=e67a9142d37d716eac0b5e54c4e0aba3&oe=61A4B0E7',
                'tagline': ''},
               {'link': '/mohammed.rikabi',
                'name': 'Mohammed Rikabi',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.18169-1/cp0/e15/q65/c7.5.59.58a/p68x68/395954_10150766256949338_1641539461_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=Ee9uoSW556YAX_SKrKJ&_nc_ht=scontent.fakl8-1.fna&oh=c9652c4ae50f2de749a8800980816bc7&oe=61A57348',
                'tagline': ''},
               {'link': '/chad.smith.10690',
                'name': 'Chad Smith',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/247574795_10159941927173541_9197074604958992627_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=FCkuxyueQ80AX99sAGQ&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=206249696145c7a9117dc789fda8ea44&oe=61A45E60',
                'tagline': ''},
               {'link': '/olivier.lequeux',
                'name': 'Olivier Lequeux',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.18169-1/cp0/e15/q65/c5.5.58.58a/p68x68/166340_10150123945229874_6808371_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=cGb94uagngsAX8QQ8a3&_nc_ht=scontent.fakl8-1.fna&oh=e449bea1d9fbc61705bebbce544e42a6&oe=61A49F21',
                'tagline': ''},
               {'link': '/pgoner',
                'name': 'Patrick George',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/243037765_10159311693873592_6970254523873923483_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=rwplDNBGtK0AX9PusuR&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=90ef80df09327f6788a177fb25e9b756&oe=61A56926',
                'tagline': ''},
               {'link': '/ben.cleator',
                'name': 'Ben Cleator',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/41869786_10156153215414081_4650966088509554688_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=zddYgyV0VlIAX-hi_qN&_nc_ht=scontent.fakl8-1.fna&oh=02201f47fdf751beb1a5a7d8cf531508&oe=61A68964',
                'tagline': ''}],
 'Following': [{'link': '/BACHCAFERUAKAKA/',
                'name': 'BACH CAFE',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p57x57/62019569_370949816863488_6027965314078081024_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=D6wRX-pWcMkAX8Cxbqg&_nc_ht=scontent.fakl8-1.fna&oh=914ed7b413432cd9c399f48b147a815c&oe=61A509ED',
                'tagline': ''},
               {'link': '/marrieddivorcedanddating',
                'name': 'Married, Divorced & Dating',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-1/cp0/p60x60/219271834_715052815940559_3449323603051501676_n.png?_nc_cat=101&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=Y0ga0NBthBwAX8SH32O&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=216cd73a24fad5d04da1d41e7d06994c&oe=6183D0A2',
                'tagline': ''},
               {'link': '/Tavlova/',
                'name': 'Tavlova',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p57x57/242742467_4307069446056697_1277958993914505650_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=8rD2gGuBEqsAX-jQfE0&_nc_ht=scontent.fakl8-1.fna&oh=29f24ad22b279026ba3e40451e4650a0&oe=61A35602',
                'tagline': ''},
               {'link': '/RadioNZMusic/',
                'name': 'RNZ Music',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/71667430_3031016560296884_8850289616788389888_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=HuN6gWcLFrQAX_oyQ7u&_nc_ht=scontent.fakl8-1.fna&oh=4a9ad92dd17aeef3faff5104f750f345&oe=61A3B039',
                'tagline': ''},
               {'link': '/mitch.david.lowe',
                'name': 'Mitch Lowe',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/46181000_10155869687698715_4551385107088277504_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=R3L4i7BHhWgAX8anazw&_nc_ht=scontent.fakl8-1.fna&oh=5fcdd88ac44567a198b869eccda273a8&oe=61A41A3B',
                'tagline': ''},
               {'link': '/letsdancewithsin',
                'name': 'Sin',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/c5.0.57.57a/p57x57/161297559_128697362589565_261764602404493210_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=c1T9kAfhKqAAX9yMJb3&_nc_ht=scontent.fakl8-1.fna&oh=912e58deec295df36a3cb110f0948781&oe=61A478F2',
                'tagline': ''},
               {'link': '/helloimcases',
                'name': 'CASES',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/162366198_577157316542973_2616666181942440428_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=EmzDPmvqntoAX8taksO&_nc_ht=scontent.fakl8-1.fna&oh=d5fd9048601d140da13c03a87f613651&oe=61A403F5',
                'tagline': ''},
               {'link': '/SlyChaos',
                'name': 'Sly Chaos',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/161695427_398065967817481_4836753368995199683_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=gMxiNQ9fUT8AX9biXr_&_nc_ht=scontent.fakl8-1.fna&oh=cf34f9ccf7c21022b4a32a4f54726078&oe=61A4A861',
                'tagline': ''},
               {'link': '/bmthofficial',
                'name': 'BRING ME THE HORIZON',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/242373855_405545937595719_3373975223733894676_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=dWGz59t5t3EAX-qdZlo&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=2df363f33744dcb6e7d7c5445340a47b&oe=61A4F20A',
                'tagline': ''},
               {'link': '/Phdcast',
                'name': 'The Phdcast',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-1/cp0/e15/q65/p57x57/244430291_255621199908950_271136204575699924_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=zDHHaD_HJUcAX9BW5Jw&_nc_ht=scontent.fakl8-1.fna&oh=84ee64d32942f5e06a2ea2903599de2c&oe=6183CD3F',
                'tagline': ''},
               {'link': '/otosanmusic',
                'name': 'Otosan',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-1/cp0/e15/q65/p60x60/239002117_254197649858571_366971733171093707_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=oSYW7dFYtuIAX-ooAEq&_nc_ht=scontent.fakl8-1.fna&oh=001bce64997062bcfd202422cacdc0cb&oe=6184DBE8',
                'tagline': ''},
               {'link': '/bavhudjs',
                'name': 'BAVHU',
                'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p60x60/161749104_193598495807794_5020458112052204377_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=1XF9CWBpqCcAX9Bjdoq&_nc_ht=scontent.fakl8-1.fna&oh=975a4737243eb32238652923fd5ff58c&oe=61A4D3AF',
                'tagline': ''}],
 'Following_count': 1128,
 'Friend_count': 3016,
 'Friends': [{'id': 100069320845673,
              'link': '/profile.php?id=100069320845673',
              'name': 'Jax Sanders',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/244423082_161691382818222_5733568056082225018_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=W_afySfygiEAX-dsZ6P&_nc_ht=scontent.fakl8-1.fna&oh=4edab759fd6a4be0caf55f338e0013bb&oe=61A58A2D',
              'tagline': ''},
             {'id': 100047005298138,
              'link': '/ashleychurchlive',
              'name': 'Ashley Church',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/84459443_106228957620614_6411181361587027968_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=B1UuCU1kk0oAX-UM5JL&_nc_ht=scontent.fakl8-1.fna&oh=587df353720388923595b77e191c6c50&oe=61A50F5F',
              'tagline': ''},
             {'id': 100073711175284,
              'link': '/gingeyboitellem',
              'name': 'Sean Francis',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/c0.0.100.100a/p100x100/244368308_102029982264041_4244155903018874271_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=7orx3xfPCrUAX_33KQw&_nc_ht=scontent.fakl8-1.fna&oh=21f9622e0ad85684001a0cdbb25d27c3&oe=61A63F9D',
              'tagline': 'Event Manager at SKR NZ'},
             {'id': 1365219119,
              'link': '/SavannahJaynex',
              'name': 'Savannah Pitcher',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/234052290_10226751222351073_1042267509675624819_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=9ISchOcLOa0AX-FXhvJ&_nc_ht=scontent.fakl8-1.fna&oh=186afc8ffea793caf38613d984d51b8d&oe=61A611F6',
              'tagline': ''},
             {'id': 503878882,
              'link': '/celia.talbot.92',
              'name': 'Celia Talbot',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/244578022_10158660777998883_4354164204794556770_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=7pGBHAn1KlwAX9m9wkd&_nc_ht=scontent.fakl8-1.fna&oh=66df01537577326cbbccfaf23f4febea&oe=61A65B84',
              'tagline': 'Reading Support at papatoetoe central'},
             {'id': 100025734502527,
              'link': '/bradley.twyman.790',
              'name': 'Bradley Twyman',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/197797733_856993441835131_239578892615491825_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=VyKK1KkYfv4AX95A1Gf&_nc_ht=scontent.fakl8-1.fna&oh=5ea9a819a6ca71abf455c30e541f928b&oe=61A5C934',
              'tagline': 'Welder and Fitter at Gilbert Sheetmetal & '
                         'Engineering'},
             {'id': 712751318,
              'link': '/krisse.mcgregor',
              'name': 'Krisse McGregor',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/248977835_10158090837011319_2011823702257379197_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=doHpVlnMFlcAX_Go8UG&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=3f02c07a31488bfd4bae13368a19e3d6&oe=61A69361',
              'tagline': 'Gerente-geral at Coffee Lab New Zealand'},
             {'id': 100050704491181,
              'link': '/profile.php?id=100050704491181',
              'name': 'Holly Murphy',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/c0.17.100.100a/p100x100/240718524_416840843349395_4272637575493307092_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=1Zm6lT6ZjS8AX9B4ayD&_nc_ht=scontent.fakl8-1.fna&oh=3e4cf9e566476fe888d64353f4fb93cb&oe=61A3A7C3',
              'tagline': ''},
             {'id': 100001376687700,
              'link': '/caleb.hemmington',
              'name': 'Caleb Hemmington',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/183922380_3952777484778102_3083332097046051556_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=TUcVMchiYCQAX-FpMUb&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=23d4c46870cc2784965ef2cb7b82c31c&oe=61A2E237',
              'tagline': 'NZ Manager at Insolence Recordings'},
             {'id': 1102274216,
              'link': '/alex.howard.9216',
              'name': 'Alex Howard',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/150789816_10224465645844324_4999128466056746156_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=iN93kC_8EWYAX_65Xx1&_nc_ht=scontent.fakl8-1.fna&oh=3624a988f2a5a5549520fb0e9b707cc3&oe=61A3B2EC',
              'tagline': 'Works at Chuffed Gifts'},
             {'id': 100009558109577,
              'link': '/joshisheredude',
              'name': 'Joshua Walker',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/246786375_2967377043590870_33573099901120269_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=Msty0hvMxZMAX_81xuf&_nc_oc=AQkdvcj5kYyFPanzT-CTQaa0_paFfNW_yixNAkHzbOiLrKaBtvE625XM90RDyR0FXH4&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=d7093106c68f5e4caab3093595b634d7&oe=61A507C7',
              'tagline': 'University of Canterbury'},
             {'id': 100003389160007,
              'link': '/alesioPeteloVili',
              'name': 'Alesio Petelo Vili',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.18169-1/cp0/e15/q65/p100x100/14718883_973011962821767_102390248253543480_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=_46C73hB7lIAX-1JEhH&_nc_ht=scontent.fakl8-1.fna&oh=29be921932bb3ceaebd8c3e0c2069298&oe=61A5427A',
              'tagline': 'Works at Les Mills'},
             {'id': 1394193444,
              'link': '/ben.hayes.1042',
              'name': 'Ben Hayes',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-1/cp0/e15/q65/p100x100/244766434_10220680142178829_643888642014759786_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=_oiYnkVv-J8AX8jZJnj&_nc_ht=scontent.fakl8-1.fna&oh=51b585b10c17059a389c3113d5bfb8dc&oe=61843F32',
              'tagline': 'Business Owner/Engineer at “HAYESMASONRY”'},
             {'id': 1147281818,
              'link': '/Mr.Swaggaliciouss',
              'name': 'Dalaine Mihaere',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/136720545_10217328044370248_541353757034757095_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=M437R7FFfqcAX9-XeNO&_nc_ht=scontent.fakl8-1.fna&oh=2e015f6a4b83309bfd553889be7f75f4&oe=61A671DB',
              'tagline': 'Works at DJ Lynch'},
             {'id': 100001927931048,
              'link': '/brooksy2099',
              'name': 'Rich Brookes',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/125870830_4710546332352918_1602423345656042098_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=KtiWi2Q0-gwAX8bzHNX&_nc_ht=scontent.fakl8-1.fna&oh=f8017d70d603b0d2fb9567e1656f207f&oe=61A69B8D',
              'tagline': 'Founder and Managing Director at Epic Media NZ'},
             {'id': 735063930,
              'link': '/IamTMLMcNaught',
              'name': 'Tom McNaught',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/130311454_10157943268233931_950019098507566642_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=iiNB-iJ-Wf8AX-yd190&_nc_ht=scontent.fakl8-1.fna&oh=444feb4c76b428b22ea70fb2243afd2f&oe=61A5AF16',
              'tagline': 'Self -Employed at Electrician'},
             {'id': 100003176577967,
              'link': '/chelsey.seth',
              'name': 'Chelsey Rennae Seth',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/175928488_3879265562189291_2786424003995838982_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=OANThrz5GFAAX-_F-My&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=1028ca9882210558570c145e7a06f8be&oe=61A50200',
              'tagline': 'Auckland, New Zealand'},
             {'id': 643230939,
              'link': '/annabelle.payne.12',
              'name': 'Annabelle Burke',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/135804738_10157516557020940_6276133662173188022_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=uAoAkaR0oqkAX9A3o6r&_nc_ht=scontent.fakl8-1.fna&oh=e9adad85e88dd2773a8f5cbbea347d95&oe=61A2DAB0',
              'tagline': 'Owner at Uncommon Agency'},
             {'id': 100000820352218,
              'link': '/Trent.vine',
              'name': 'Trent Vine',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/148227858_3675437805826862_8884530617132335556_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=xMw9rv_HqlMAX83vUQc&_nc_ht=scontent.fakl8-1.fna&oh=923aaf4eb5762bdc8aa7936cfabcf149&oe=61A3AD2E',
              'tagline': 'Artist at Reigning Records'},
             {'id': 100006643515372,
              'link': '/jade.hakaraia.9',
              'name': 'Jade Hakaraia',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-1/cp0/e15/q65/p100x100/243104713_3169880879909998_7442579281985602715_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=ur0vdmhBbkUAX8kyXF0&_nc_ht=scontent.fakl8-1.fna&oh=47c93b88bf5c6ea833e95a2500e0d572&oe=6184A984',
              'tagline': 'Awatapu College'},
             {'id': 100000561640428,
              'link': '/euwyn.daniels',
              'name': 'Euwyn Daniels',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/29356646_1984895791539123_4457130447754756096_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=ovuZqHdTw6cAX89kHXN&_nc_ht=scontent.fakl8-1.fna&oh=bf125cd2473fb510d8c8f8b04fe6dcb3&oe=61A31FE8',
              'tagline': 'Works at Self-Employed'},
             {'id': 588074376,
              'link': '/amy.m.mcintyre',
              'name': 'Amy Mac',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/170277404_10160767441449377_2824705954053823800_n.jpg?_nc_cat=111&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=z_JxNQzMgJkAX_2akvn&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=b8e3807f13fb8114bc4d4d2736ca25a8&oe=61A3590A',
              'tagline': 'North Shore, New Zealand'},
             {'id': 1040794868,
              'link': '/kristin.paddy',
              'name': 'Kristin Paddy',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/158461853_10221396296990472_1357250431600494608_n.jpg?_nc_cat=106&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=-rABwqXt78AAX-P7TkA&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=4030fcab40226b4534b0a32a92a5825a&oe=61A48298',
              'tagline': 'Auckland, New Zealand'},
             {'id': 100065068450202,
              'link': '/profile.php?id=100065068450202',
              'name': 'Jono Taylor',
              'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-1/cp0/e15/q65/p100x100/242696951_229139745931639_381003356898551233_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=dbb9e7&efg=eyJpIjoidCJ9&_nc_ohc=aNkH-5d80MUAX_QPj7x&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=550af2dd32fcfd50f8c5b61415692d09&oe=61A5BD69',
              'tagline': ''}],
 'Life Events': '',
 'Name': 'Rachel Flood',
 'Places Lived': 'Auckland, New Zealand\n'
                 'Current City\n'
                 'Auckland, New Zealand\n'
                 'Hometown',
 'Work': 'MediaWorks New Zealand\n'
         'Auckland, New Zealand\n'
         'Raggamuffin Music Festival\n'
         'The Music Agency\n'
         'Booking Agent and Tour Manager\n'
         'Auckland, New Zealand',
 'cover_photo': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/123167057_10159867216422079_920600565410338489_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=dd9801&efg=eyJpIjoidCJ9&_nc_ohc=uP6HkKzap38AX_qTxaR&_nc_ht=scontent.fakl8-1.fna&oh=cd6c3f42a64fb316b594a4798b556828&oe=61A4BA00&manual_redirect=1',
 'cover_photo_text': "Cover Photo: Rachel Flood's photo.",
 'id': '620017078',
 'profile_picture': 'https://scontent.fakl8-1.fna.fbcdn.net/v/t39.30808-6/fr/cp0/e15/q65/244507075_10160916398492079_4161667232231154684_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=85a577&efg=eyJpIjoidCJ9&_nc_ohc=lHokNEvoyfgAX-D1CXk&tn=G0A6CIFFIGzhHbRm&_nc_ht=scontent.fakl8-1.fna&oh=b6582eca9adde7068cbf275b31e1e088&oe=61838BB5&manual_redirect=1'}
```

**Comment by giuseppe-toscano** [comment]
Perfect, thank you!

**Comment by giuseppe-toscano** [comment]
@neon-ninja Testing the new version, I found that "Friend_count" has some problems when you have common friends with that person. In particular, its value is the concatenation between the total number of friends and the number of common friends. For example:
Total number of friends = 1000
Common friends between me and that person = 200
Friend_count = 1000200
Furthermore, the number to limit the list of friends/followers/following does not work.  Analysing the response obtained with the code that you gave me `pprint(get_profile("rachellouiseflood", cookies="cookies.json", followers=5, following=5, friends=5))` does not return exactly 5 followers, 5 following and 5 friends but 12 followers, 12 following and 24 friends. Why?

**Comment by neon-ninja** [comment]
The reason is those come in pages of various sizes. The count means - get pages until you have at least this many.

**Comment by giuseppe-toscano** [comment]
> The reason is those come in pages of various sizes. The count means - get pages until you have at least this many.

Ah ok, now it's clear. Thank you.

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/f80de7da859f72c372536263ced065111fe09ab7 should fix the issue with the friend count

**Comment by lucawen** [comment]
Still not working. Facebook seens to changed the way that show this numbers. The content in /about is now inserted over javascript with random class names.

**Comment by neon-ninja** [comment]
@lucawen can you post the code you used? So I can try reproduce this issue
