### ISSUE TITLE
get_profile "KeyError: 'id'

### ISSUE THREAD

**Issue by NguyenKzHSpace** [kevinzg/facebook-scraper#750]
Hi everyone.
When I use the function "get_profile(account="...", likes = True)", I get this error.
Traceback:
  facebook_scraper/facebook_scraper.py", line 471, in get_profile
  if result["id"] and kwargs.get("likes"):
 "KeyError: 'id'.

**Comment by Vanguard-52236** [comment]
I can confirm the same error, with cookies and language set to English.

**Comment by NiharKashyap** [comment]
Same issue. Was working fine till yesterday. Started throwing this error today

**Comment by NiharKashyap** [comment]
The issue was in line 471 of /facebook_scraper.py file. 

I solved it by changing this line:

```
if match:
            result["id"] = match.group(1)
```

to

```
if match:
            result["id"] = match.group(1)
        else:
            result["id"] = None
```

Normally if there is no match `result["id"]` will not be set and `if result["id"] and kwargs.get("likes")` will throw key not found error. With the above modification `result["id"]` will be set to None.

**Comment by NguyenKzHSpace** [comment]
**I fixed it by:**
file facebook_scraper.py line 380:
`match = re.search(r'entity_id:(\d+),', response.html.html)`
to
`match = re.search(r'entity_id:(\d)+', response.html.html)`

*Because facebook-scraper get profile id by regex: 
Html text is: `entity_id:12334455,...}]`
`r'entity_id:(\d+),'` 
result: `entity_id:12334455,`
#But in this case, we have:
`entity_id:12334455}]`
#So we change regex to: `r'entity_id:(\d)+'`
result:  `entity_id:12334455`

**Comment by Singer-sama** [comment]
> **I fixed it by:** file facebook_scraper.py line 380: `match = re.search(r'entity_id:(\d+),', response.html.html)` to `match = re.search(r'entity_id:(\d)+', response.html.html)`
> 
> *Because facebook-scraper get profile id by regex: Html text is: `entity_id:12334455,...}]` #Old regex; `r'entity_id:(\d+),'` #Result: `entity_id:12334455,` #But in this case, we have: `entity_id:12334455}]` #So we change regex to: `r'entity_id:(\d)+'` result: `entity_id:12334455`

@NguyenKzHSpace 
that does not work and this code introduces another bug as by moving the '+' out of the group , the group will only match the last digit of the id [if there is a match in the first place]

what works for me is replacing 
```
        match = re.search(r'entity_id:(\d)+', response.html.html)        
        if match:
            result["id"] = match.group(1)
```
with
```
        match = re.search(r'entity_id:(\d+)', response.html.html)   
        match2 = re.search(r'profile_id&quot;:(\d+)', response.html.html)      
        if match:
            result["id"] = match.group(1)
        elif match2:
            result["id"] = match2.group(1)
        else:
            # raise Exception or something
            pass

```

**Comment by NguyenKzHSpace** [comment]
> > **I fixed it by:** file facebook_scraper.py line 380: `match = re.search(r'entity_id:(\d+),', response.html.html)` to `match = re.search(r'entity_id:(\d)+', response.html.html)`
> > *Because facebook-scraper get profile id by regex: Html text is: `entity_id:12334455,...}]` #Old regex; `r'entity_id:(\d+),'` #Result: `entity_id:12334455,` #But in this case, we have: `entity_id:12334455}]` #So we change regex to: `r'entity_id:(\d)+'` result: `entity_id:12334455`
> 
> @NguyenKzHSpace that does not work and this code introduces another bug as by moving the '+' out of the group , the group will only match the last digit of the id [if there is a match in the first place]
> 
> what works for me is replacing
> 
> ```
>         match = re.search(r'entity_id:(\d)+', response.html.html)        
>         if match:
>             result["id"] = match.group(1)
> ```
> 
> with
> 
> ```
>         match = re.search(r'entity_id:(\d+)', response.html.html)   
>         match2 = re.search(r'profile_id&quot;:(\d+)', response.html.html)      
>         if match:
>             result["id"] = match.group(1)
>         elif match2:
>             result["id"] = match2.group(1)
>         else:
>             # raise Exception or something
>             pass
> ```

In this case:
`r'entity_id:(\d+)'` and `r'entity_id:(\d)+'` have the same result.
`(\d+)`: **group**(**repeat**(\d) while finding a character isn't a digit): entity_id:12344657aaa => entity_id:12344567
`(\d)+`: **repeat**(**group**(\d)) while finding a character isn't a digit: entity_id:12344657aaa => entity_id:12344567

I think your code is work:
`match2 = re.search(r'profile_id&quot;:(\d+)', response.html.html) `

**Comment by Singer-sama** [comment]
@NguyenKzHSpace 
explanation of why it's not the same :
![image](https://user-images.githubusercontent.com/69518425/166990277-a09443fd-ba0e-45f9-9073-3678f7de6801.png)

**Comment by NguyenKzHSpace** [comment]
> @NguyenKzHSpace explanation of why it's not the same : ![image](https://user-images.githubusercontent.com/69518425/166990277-a09443fd-ba0e-45f9-9073-3678f7de6801.png)
OK, I'm wrong, but in my code, I use group() not group(1), and remove "entity_id" from the result, so this is the same result.
![image](https://user-images.githubusercontent.com/92080431/167056742-fd3ab387-7cb9-4dce-a49b-8d1e1d9f4110.png)

**Comment by Suizer** [comment]
I got the same error

**Comment by neon-ninja** [comment]
https://github.com/kevinzg/facebook-scraper/commit/23bddcea388d09950b8e43532cbf343c44c1d161 should fix this

**Comment by izardy** [comment]
tried the latest fix on v0.2.56 but the problem still exist , so what I did is just deleting line 477 - 534 since I don't really need number of likes.

> 

tried the latest fix on v0.2.56 but the problem still exist , so what I did is just deleting line 477 - 534 since I don't really need number of likes.

**Comment by Vanguard-52236** [comment]
This worked for me. I was having seemingly the same issue. `KeyError: 'id'`

v0.2.56 resolved this. Thanks!
